services:

  # Table tl_page

  ## tl_page.title
  cyberspectrum_i18n.contao.extractor.tl_page.title:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'title'
    tags:
      - { name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectContaoExtractorsPass::TAG_CONTAO_EXTRACTOR, table: 'tl_page' }

  ## tl_page.alias
  cyberspectrum_i18n.contao.extractor.tl_page.alias:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'alias'
    tags:
      - { name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectContaoExtractorsPass::TAG_CONTAO_EXTRACTOR, table: 'tl_page' }

  ## tl_page.pageTitle
  cyberspectrum_i18n.contao.extractor.tl_page.page_title:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'pageTitle'
    tags:
      - { name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectContaoExtractorsPass::TAG_CONTAO_EXTRACTOR, table: 'tl_page' }

  # Table tl_article

  ## tl_article.title
  cyberspectrum_i18n.contao.extractor.tl_article.title:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'title'
    tags:
      - { name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectContaoExtractorsPass::TAG_CONTAO_EXTRACTOR, table: 'tl_article' }

  ## tl_article.alias
  cyberspectrum_i18n.contao.extractor.tl_article.alias:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'alias'
    tags:
      - { name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectContaoExtractorsPass::TAG_CONTAO_EXTRACTOR, table: 'tl_article' }

  # Table tl_content

  ## tl_content.headline
  cyberspectrum_i18n.contao.extractor.tl_content.headline:
    class: CyberSpectrum\I18N\Contao\Extractor\SerializingCompoundExtractor
    arguments:
      - 'headline'
      - ['@cyberspectrum_i18n.contao.extractor.tl_content.headline.value']
    tags:
      - { name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectContaoExtractorsPass::TAG_CONTAO_EXTRACTOR, table: 'tl_content' }
      - {
          name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectExtractorConditionsPass::TAG_CONTAO_EXTRACTOR_CONDITION,
          type: expression,
          expression: "row.type in ['headline', 'text']"
        }

  cyberspectrum_i18n.contao.extractor.tl_content.headline.value:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'value'

  ## tl_content.html
  cyberspectrum_i18n.contao.extractor.tl_content.html:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'html'
    tags:
      - { name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectContaoExtractorsPass::TAG_CONTAO_EXTRACTOR, table: 'tl_content' }
      - {
          name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectExtractorConditionsPass::TAG_CONTAO_EXTRACTOR_CONDITION,
          type: expression,
          expression: "row.type in ['html']"
        }

  ## tl_content.tableitems
  cyberspectrum_i18n.contao.extractor.tl_content.tableitems:
    class: CyberSpectrum\I18N\Contao\Extractor\TableExtractor
    arguments:
      - 'tableitems'
    tags:
      - { name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectContaoExtractorsPass::TAG_CONTAO_EXTRACTOR, table: 'tl_content' }
      - {
          name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectExtractorConditionsPass::TAG_CONTAO_EXTRACTOR_CONDITION,
          type: expression,
          expression: "row.type in ['table']"
        }

  ## tl_content.text
  cyberspectrum_i18n.contao.extractor.tl_content.text:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'text'
    tags:
      - { name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectContaoExtractorsPass::TAG_CONTAO_EXTRACTOR, table: 'tl_content' }
      - {
          name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectExtractorConditionsPass::TAG_CONTAO_EXTRACTOR_CONDITION,
          type: expression,
          expression: "row.type in ['text']"
        }

  ## tl_content.mooHeadline
  cyberspectrum_i18n.contao.extractor.tl_content.moo_headline:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'mooHeadline'
    tags:
      - { name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectContaoExtractorsPass::TAG_CONTAO_EXTRACTOR, table: 'tl_content' }
      - {
          name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectExtractorConditionsPass::TAG_CONTAO_EXTRACTOR_CONDITION,
          type: expression,
          expression: "row.type in ['accordionStart', 'accordionSingle']"
        }
