services:

  # Table tl_content

  ## tl_content.rsce_data
  cyberspectrum_i18n.contao.extractor.tl_content.rsce_data:
    class: CyberSpectrum\I18N\Contao\Extractor\JsonSerializingCompoundExtractor
    arguments:
      - 'rsce_data'
      -
        - '@cyberspectrum_i18n.contao.extractor.tl_content.rsce_data.link_label'
        - '@cyberspectrum_i18n.contao.extractor.tl_content.rsce_data.boxes'
        - '@cyberspectrum_i18n.contao.extractor.tl_content.rsce_data.text'
    tags:
      - { name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectContaoExtractorsPass::TAG_CONTAO_EXTRACTOR, table: 'tl_content' }
      - {
          name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectExtractorConditionsPass::TAG_CONTAO_EXTRACTOR_CONDITION,
          type: expression,
          expression: "row.type in ['rsce_tao_feature_box', 'rsce_field_boxes']"
        }

  ## tl_content.rsce_data.link_label
  cyberspectrum_i18n.contao.extractor.tl_content.rsce_data.link_label:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'linkLabel'

  cyberspectrum_i18n.contao.extractor.tl_content.rsce_data.text:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'text'

  ## tl_content.rsce_data.boxes
  cyberspectrum_i18n.contao.extractor.tl_content.rsce_data.boxes:
    class: CyberSpectrum\I18N\Contao\Extractor\ArrayExtractor
    arguments:
      - 'boxes'
      -
        - '@cyberspectrum_i18n.contao.extractor.tl_content.rsce_data.boxes.headline'
        - '@cyberspectrum_i18n.contao.extractor.tl_content.rsce_data.boxes.text'
        - '@cyberspectrum_i18n.contao.extractor.tl_content.rsce_data.boxes.link_label'

  cyberspectrum_i18n.contao.extractor.tl_content.rsce_data.boxes.headline:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'headline'

  cyberspectrum_i18n.contao.extractor.tl_content.rsce_data.boxes.text:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'text'

  cyberspectrum_i18n.contao.extractor.tl_content.rsce_data.boxes.link_label:
    class: CyberSpectrum\I18N\Contao\Extractor\TextExtractor
    arguments:
      - 'linkLabel'
