services:
  CyberSpectrum\I18N\Contao\ContaoDictionaryProvider:
    arguments:
      - '@database_connection'
      - '@CyberSpectrum\I18N\Contao\ExtractorFactory'
      - '@cyberspectrum_i18n.contao.default_map_builder'
    calls:
      - method: 'setLogger'
        arguments: ['@logger']
    tags:
      - { name: !php/const CyberSpectrum\I18NBundle\DependencyInjection\CompilerPass\CollectDictionaryProvidersPass::TAG_DICTIONARY_PROVIDER, provider: 'contao' }

  CyberSpectrum\I18N\ContaoBundle\Command\DebugMapCommand:
    arguments:
      - '@cyberspectrum_i18n.contao.default_map_builder'
    tags:
      - { name: console.command }

  cyberspectrum_i18n.expression_language:
    class: Symfony\Component\ExpressionLanguage\ExpressionLanguage
    # FIXME: add some cache here.

  CyberSpectrum\I18N\Contao\ExtractorFactory:
    arguments:
      - '%cyberspectrum_i18n.contao.extractors%'
      - '@cyberspectrum_i18n.contao.extractor_container'
    calls:
      - method: 'setLogger'
        arguments: ['@logger']

  cyberspectrum_i18n.contao.extractor_container:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    arguments:
      - []
    tags: ['container.service_locator']

  CyberSpectrum\I18N\ContaoBundle\Controller\ContaoInspectProblemsController:
    arguments:
      - '@templating'
      - '@cyberspectrum_i18n.contao.default_map_builder'
      - '@cyberspectrum_i18n.contao.csrf.token_manager'
      - '%contao.csrf_token_name%'
    tags: ['controller.service_arguments']

  CyberSpectrum\I18N\ContaoBundle\FormType\InspectMappingFormType:
    arguments:
      - '@cyberspectrum_i18n.contao.default_map_builder'
      - '%contao.csrf_token_name%'
    tags: [form.type]

  CyberSpectrum\I18N\Contao\ContaoDictionaryDefinitionBuilder:
