services:
  CyberSpectrum\I18N\Contao\Mapping\Terminal42ChangeLanguage\ContaoDatabase:
    arguments:
      - '@database_connection'

  CyberSpectrum\I18N\Contao\Mapping\Terminal42ChangeLanguage\MapBuilder:
    arguments:
      - '@CyberSpectrum\I18N\Contao\Mapping\Terminal42ChangeLanguage\ContaoDatabase'
    calls:
      - method: 'setLogger'
        arguments: ['@logger']
