dist: xenial

os: linux

addons:
  apt:
    packages:
      - ant-optional

language: php

php:
  - '7.4'
  - '7.3'
  - '7.2'

env:
  - SYMFONY_VERSION='^5.0'
  - SYMFONY_VERSION='^4.0'
  - SYMFONY_VERSION='^3.0'

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update && composer --version
  # Contao currently conflicts with symfony 5.0 config
  # - travis_retry composer require symfony/config ${SYMFONY_VERSION} --no-update
  - travis_retry composer require symfony/dependency-injection ${SYMFONY_VERSION} --no-update
  - travis_retry composer require symfony/form ${SYMFONY_VERSION} --no-update
  - travis_retry composer require symfony/framework-bundle ${SYMFONY_VERSION} --no-update
  - travis_retry composer require symfony/http-kernel ${SYMFONY_VERSION} --no-update
  - travis_retry composer require symfony/http-foundation ${SYMFONY_VERSION} --no-update
  - travis_retry composer require symfony/options-resolver ${SYMFONY_VERSION} --no-update
  - travis_retry composer require symfony/routing ${SYMFONY_VERSION} --no-update
  - travis_retry composer require symfony/security-csrf ${SYMFONY_VERSION} --no-update
  - travis_retry composer require symfony/templating ${SYMFONY_VERSION} --no-update
  - >
    if [ "x${TRAVIS_TAG}" != "x" ]; then
      COMPOSER_ROOT_VERSION=${TRAVIS_TAG} travis_retry composer update --prefer-dist --no-interaction;
    else
      COMPOSER_ROOT_VERSION=$([[ ${TRAVIS_BRANCH} =~ hotfix/([0-9.]*(-(alpha|beta|rc)[0-9]+)?) ]] \
        && echo ${BASH_REMATCH[1]} \
        || echo dev-${TRAVIS_BRANCH}) \
        travis_retry composer update --prefer-dist --no-interaction;
    fi

script: ant -keep-going

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647

cache:
  directories:
    - vendor
