services:
  CyberSpectrum\I18N\MetaModels\MetaModelDictionaryProvider:
    arguments:
      - '@metamodels.factory'
      - '@CyberSpectrum\I18N\MetaModels\MetaModelHandlerFactory'
    calls:
      - method: 'setLogger'
        arguments: ['@logger']
    tags:
      - { name: !php/const CyberSpectrum\I18NBundle\DependencyInjection\CompilerPass\CollectDictionaryProvidersPass::TAG_DICTIONARY_PROVIDER, provider: 'metamodels' }

  CyberSpectrum\I18N\MetaModels\MetaModelHandlerFactory:
    arguments:
      - '@cyberspectrum_i18n.metamodels.attribute_handler_factories'

  cyberspectrum_i18n.metamodels.attribute_handler_factories:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    arguments:
      - []
    tags: ['container.service_locator']

  CyberSpectrum\I18N\MetaModels\MetaModelTextHandlerFactory:
    tags:
      - name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectMetaModelAttributeHandlerPass::TAG_ATTRIBUTE_HANDLER_FACTORY
        type: MetaModels\AttributeTranslatedTextBundle\Attribute\TranslatedText
      - name: !php/const CyberSpectrum\I18N\ContaoBundle\DependencyInjection\CompilerPass\CollectMetaModelAttributeHandlerPass::TAG_ATTRIBUTE_HANDLER_FACTORY
        type: MetaModels\AttributeTranslatedLongtextBundle\Attribute\TranslatedLongtext

  CyberSpectrum\I18N\MetaModels\MetaModelDictionaryDefinitionBuilder:
